### ISSUE TITLE
pre-commit

### ISSUE THREAD

**Issue by florian-dacosta** [akretion/docky-odoo-template-shared#23]
This issue is here to document what I have done, to use pre-commit with the current template.
This is not the best way and we'll need to improve ourselves, but I want to note the issues I did meet and the workaround until we have a better solution.

For now, if we want to have pre-commit with all the oca linter one solution is to do the following

in /odoo/local-src : copier copy --UNSAFE https://github.com/OCA/oca-addons-repo-template.git .
Answer all questions and then remove the generated repo /odoo/local-src/.github

Then, as pre-commit run always from the root of the git repository, you may want to ignore some files from the project, that are not linted the same ways as OCA (and we don't really want to maintain a linting each time there is a change in OCA...)
```

bin/*|
.gitlab-ci.yml|
docker-compose.yml|ci.secrets.docker-compose.yml|ci.docker-compose.yml|prod.docker-compose.yml|prod.secrets.docker-compose.yml|
.copier-answers.yml|
odoo/spec.yam
```
 + add config file from oca that are not linted...
`eslint.config.cjs|prettier.config.cjs`

And it seems we have to have a symbolic link at the root of the project with eslint.config.cjs for it to work propertly 
`ln -s odoo/local-src/eslint.config.cjs eslint.config.cjs`

In option, you can remove the `missing-readme` error if you do not want to manage a readme file in all custom modules.

**Comment by metaminux** [comment]
Salut @florian-dacosta 

Je participe à la discussion, histoire de voir si on peut dégager une pratique commune

## Utiliser les dotfiles OCA (`oca-addons-repo-template`) dans le sous-répertoire "odoo/local-src" d'un projet `docky-odoo-template-shared`

Objectif : appliquer les conventions OCA (pre-commit, lint, README auto-générés...) uniquement sur `odoo/local-src`, sans toucher au reste du projet géré par le template `docky-odoo-template-shared`.

### 1. Récupération des dotfiles

```bash
copier copy https://github.com/OCA/oca-addons-repo-template odoo/local-src
```

Pas besoin de l'option `--answers-file` : `copier copy` écrit `.copier-answers.yml` par défaut **dans le répertoire de destination** (`odoo/local-src/.copier-answers.yml`), donc aucun conflit avec le `.copier-answers.yml` du template `docky-odoo-template-shared` à la racine du projet.

### 2. Mise à jour ultérieure

```bash
copier update odoo/local-src
```

On peut exécuter cette commande depuis la racine du projet.

### 3. Adaptations du `.pre-commit-config.yaml` généré

Deux familles de correctifs ont été nécessaires.

**a) Portée du fichier sur le sous-répertoire** (pur problème de chemin) :
- ajout d'un `files: ^odoo/local-src/` global en tête de fichier, pour que *tous* les hooks (y compris ceux sans `files:` propre comme `ruff` ou `trailing-whitespace`) ne s'appliquent qu'à ce sous-répertoire ;
- préfixage par `odoo/local-src/` des motifs `exclude` ancrés (`^...`) qui référencent des fichiers précis : `README.md`, `.github/`, `.copier-answers.yml`, `setup/`, `eslint.config.cjs`, `prettier.config.cjs`, `docs/_templates/` ;
- `--rcfile=.pylintrc` → `--rcfile=odoo/local-src/.pylintrc` (idem `.pylintrc-mandatory`).

**b) Contournement du cwd figé de plusieurs scripts OCA/whool.** pre-commit exécute toujours ses hooks avec le *working directory* à la racine du dépôt git et pas à l'emplacement du `.pre-commit-config.yaml`. Or plusieurs outils (`whool init`, et une partie des scripts `OCA/maintainer-tools`) scannent/écrivent en se basant sur le répertoire courant du processus, indépendamment de tout argument `--addons-dir`. `gen_external_dependencies.py` n'a même aucun parsing de `sys.argv`.

Correctif : ajouter un champ `entry` pour chaque hook concerné pour forcer le `cd` avant l'exécution réelle (pre-commit autorise cette surcharge pour un hook référencé depuis un dépôt distant ; l'environnement/venv construit par pre-commit reste actif) :

```yaml
entry: bash -c 'cd odoo/local-src && <commande> "$@"' --
```

Hooks concernés : `whool-init`, `oca-update-pre-commit-excluded-addons`, `oca-fix-manifest-website`, `oca-gen-addon-readme`, `oca-gen-external-dependencies`, `oca-gen-addons-table`.

Exception : `oca-gen-addon-icon` honore correctement un vrai `--addons-dir`, pas besoin de surcharger `entry` pour celui-là, un simple `args: [--addons-dir=odoo/local-src, ...]` suffit et permet de stocker une seule fois le fichier image utilisé pour le client à la racine du projet (Remarque, on pourrait aussi le stocker dans `odoo/local-src`).

### Fichier final

Pour un projet 18.0 (version copier template = v1.44) ça donne ça, au final

```yaml
files: ^odoo/local-src/
exclude: |
  (?x)
  ^odoo/local-src/setup/|/static/description/index\.html$|
  .svg$|/tests/([^/]+/)?cassettes/|^odoo/local-src/\.copier-answers\.yml$|^odoo/local-src/\.github/|^odoo/local-src/eslint.config.cjs|^odoo/local-src/prettier.config.cjs|
  ^odoo/local-src/README\.md$|
  /static/(src/)?lib/|
  ^odoo/local-src/docs/_templates/.*\.html$|
  readme/.*\.(rst|md)$|
  /build/|/dist/|
  /tests/samples/.*|
  (LICENSE.*|COPYING.*)
default_language_version:
  python: python3.12
  node: "22.9.0"
repos:
  - repo: local
    hooks:
      - id: forbidden-files
        name: forbidden files
        entry: found forbidden files; remove them
        language: fail
        files: "\\.rej$"
      - id: en-po-files
        name: en.po files cannot exist
        entry: found a en.po file
        language: fail
        files: '[a-zA-Z0-9_]*/i18n/en\.po$'
      - id: obsolete dotfiles
        name: obsolete dotfiles
        entry: found obsolete files; remove them
        files: '^odoo/local-src/(\.travis\.yml|\.t2d\.yml|CONTRIBUTING\.md|\.prettierrc\.yml|\.eslintrc\.yml)$'
        language: fail
  - repo: https://github.com/sbidoul/whool
    rev: v1.3
    hooks:
      - id: whool-init
        entry: bash -c 'cd odoo/local-src && whool init "$@"' --
  - repo: https://github.com/oca/maintainer-tools
    rev: 31bdbd8e4cb94be6534f0e82b1cafb84a455f671
    hooks:
      - id: oca-update-pre-commit-excluded-addons
        entry: bash -c 'cd odoo/local-src && oca-update-pre-commit-excluded-addons "$@"' --
      - id: oca-fix-manifest-website
        entry: bash -c 'cd odoo/local-src && oca-fix-manifest-website "$@"' --
        args: ["https://gitlab.akretion.com/akretion/afocg"]
      - id: oca-gen-addon-readme
        entry: bash -c 'cd odoo/local-src && oca-gen-addon-readme "$@"' --
        args:
          - --addons-dir=.
          - --branch=18.0
          - --org-name=akretion
          - --repo-name=afocg
          - --if-source-changed
          - --keep-source-digest
          - --convert-fragments-to-markdown
      - id: oca-gen-external-dependencies
        entry: bash -c 'cd odoo/local-src && oca-gen-external-dependencies "$@"' --
      - id: oca-gen-addon-icon
        args:
          - --addons-dir=odoo/local-src
          - --src-icon=customer_icon.svg
      - id: oca-gen-addons-table
        entry: bash -c 'cd odoo/local-src && oca-gen-addons-table "$@"' --
  - repo: https://github.com/OCA/odoo-pre-commit-hooks
    rev: v0.0.33
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po
        args:
          - --disable=po-pretty-format
  - repo: local
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        entry: prettier
        args:
          - --write
          - --list-different
          - --ignore-unknown
        types: [text]
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
        language: node
        additional_dependencies:
          - "prettier@3.3.3"
          - "@prettier/plugin-xml@3.4.1"
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        args:
          - --color
          - --fix
        verbose: true
        types: [javascript]
        language: node
        additional_dependencies:
          - "eslint@9.12.0"
          - "eslint-plugin-jsdoc@50.3.1"
          - "globals@16.0.0"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.1.3
    hooks:
      - id: pylint_odoo
        name: pylint with optional checks
        args:
          - --rcfile=odoo/local-src/.pylintrc
          - --exit-zero
        verbose: true
      - id: pylint_odoo
        args:
          - --rcfile=odoo/local-src/.pylintrc-mandatory
```

### 4. Activation automatique au commit

On n'a pas de `.pre-commit-config.yaml` à la racine, donc installation directe depuis la racine du dépôt :

```bash
pre-commit install --config odoo/local-src/.pre-commit-config.yaml
```

### Points d'attention

- Pas de lien symbolique nécessaire pour `.pylintrc` et consorts : pre-commit exécute toujours ses hooks avec le cwd à la racine git, donc les chemins d'arguments doivent être explicites (`odoo/local-src/...`) plutôt que résolus via un lien à la racine.
